[theme]
primaryColor = "#4CAF50"
backgroundColor = "#0e0e0e"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#ffffff"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = true
headless = true
maxUploadSize = 200

[browser]
gatherUsageStats = false
